const eldinnVarClassesMap: Record<string, string> = {
    blinded: "eldinn-blinded",
    charmed: "eldinn-charmed",
    deafened: "eldinn-deaftened",
    exhaustion1: "eldinn-exhaustion1",
    exhaustion2: "eldinn-exhaustion2",
    exhaustion3: "eldinn-exhaustion3",
    exhaustion4: "eldinn-exhaustion4",
    exhaustion5: "eldinn-exhaustion5",
    exhaustion6: "eldinn-exhaustion6",
    frightened: "eldinn-frightened",
    grappled: "eldinn-grappled",
    incapacitated: "eldinn-incapacitated",
    unconscious: "eldinn-inconscious",
    invisible: "eldinn-invisible",
    paralyzed: "eldinn-paralyzed",
    petrified: "eldinn-petrified",
    poisoned: "eldinn-poisoned",
    prone: "eldinn-prone",
    restrained: "eldinn-restrained",
    stunned: "eldinn-stunned",
}
